image: node:18

stages:
  - build
  - deploy_setup
  - deploy

.distributed:
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline
    - NX_HEAD=$CI_COMMIT_SHA
    - NX_BASE=${CI_MERGE_REQUEST_DIFF_BASE_SHA:-$CI_COMMIT_BEFORE_SHA}

variables:
  GIT_DEPTH: 0

build:
  stage: build
  extends: .distributed
  script:
    - npx nx affected --base=$NX_BASE --head=$NX_HEAD -t build --parallel=3

generate-deploy-child-process:
  stage: deploy_setup
  extends: .distributed
  script:
    - npx nx run atlas-form:deploy --base ${NX_BASE} --head ${NX_HEAD} --branch ${CI_COMMIT_BRANCH}
  artifacts:
    paths:
      - affected-deploy-ci.yaml

deploy:
  stage: deploy
  only:
    - merge_requests
    - main
  trigger:
    include:
      - artifact: affected-deploy-ci.yaml
        job: generate-deploy-child-process
    strategy: depend
